title: [Reda Said Cybersecurity Projects]
description: Welcome! This portfolio showcases hands-on cybersecurity projects, incident response documentation, and research in SOC analysis, threat intelligence, and risk operations. All work reflects a commitment to practical skill-building, technical rigor, and clear communication.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
